name: historial_exit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  fluttertoast: ^8.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.4.0
  firebase_database: ^10.4.8
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.15.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
